### ISSUE TITLE
iOS Target version

### ISSUE THREAD

**Issue by rgustavsson** [rediska1114/capacitor-app-tracking-transparency#1]
Hello!

Now that Capacitor has minimum target of iOS 12, will you be updating this plugin?

**Comment by rediska1114** [comment]
Hey @rgustavsson!

At the moment, I personally use Capacitor 2 and therefore have not yet updated the plugin to match the new version.

I will look at your PR and update the plugin soon

**Comment by rediska1114** [comment]
@rgustavsson

Done, please update to the latest version
