### ISSUE TITLE
Capacitor 3

### ISSUE THREAD

**Issue by maxbauer** [rediska1114/capacitor-app-tracking-transparency#3]
Hi,
at first, thanks a lot for providing this plugin. 
Is it planned to migrate it to Capacitor 3?

**Comment by rediska1114** [comment]
Hello, @maxbauer! 

The latest version of the plugin should already support Capacitor 3

Please check this issue https://github.com/rediska1114/capacitor-app-tracking-transparency/issues/1

**Comment by maxbauer** [comment]
I used the instructions from the Readme in this repo, then I got a error. But with the instructions on npm it seems to work.
