### ISSUE TITLE
Both GetStatus and GetPermission return undefined

### ISSUE THREAD

**Issue by BenjaminDish** [rediska1114/capacitor-app-tracking-transparency#4]
Hello,

I implemented your plugin exactly as shown in doc. I always get undefined as the result of the promises returned by both functions. It works because I can see the permission demand, but it doesn't return a valid status.

Can you help me ?

**Comment by rediska1114** [comment]
It was fixed in #5 

Please upgrade to version 0.1.5 (for Capacitor v2) or to version 1.1.5 (for Capacitor v3)
